### ISSUE TITLE
2D Traverser

### ISSUE THREAD

**Issue by tay10r** [madmann91/bvh#13]
This library can easily be used for 2D contexts as well. The only additional feature it would need is a traverser that takes advantage of the simpler AABB test. Here's the AABB test, where `x` and `y` are the pixel coordinates.

```cxx
float intersect(float x, float y, const Bvh<float>::Node& node)
{
  if ((x < node.bounds[0])
   || (x > node.bounds[1])
   || (y < node.bounds[2])
   || (y > node.bounds[3])) {
    return std::numeric_limits<float>::infinity();
  }
  return std::min(node.bounds[4], node.bounds[5]);
}
```

This is how I currently use this library for a 2D renderer that I've been working on. Would you be interested in a PR for this? The only thing I'd need to do is add support for the `Intersector` template parameter and `Statistics` parameter, the rest is already written and quite simple.

**Comment by madmann91** [comment]
Do you mean traversing a 2D BVH, or traversing a 3D BVH with a plane instead of a ray?

**Comment by tay10r** [comment]
Traversing a 3D BVH with a point from an image plane. I consider the 3D BVH useful because the scene primitives still have a Z index.

**Comment by madmann91** [comment]
If all you need is a 2D BVH, it might make sense not to use this library because BVH nodes can be made smaller, and the split heuristic should probably be changed (the SAH might not represent the cost of your traversal operation well). Seeing this is a not so common use of the library, I'd rather keep this separate if possible. If you want, I can add a `NodeIntersector` template parameter to the `SingleRayTraverser` class, and you can plug your code there. Not sure if that helps?

**Comment by tay10r** [comment]
It can stay separate then. I guess it's not too difficult that on the chance that someone else needs it, they can do it themselves with relatively little effort.

**Comment by madmann91** [comment]
I have refactored the code to allow custom node intersectors in the `SingleRayTraverser` class. Let me know if this helps (or not?).

**Comment by tay10r** [comment]
@madmann91 Yes, that's helpful! That definitely makes it easier to retrofit into a 2D renderer. I'll have to a take another look at the node intersectors you added at some point, looks pretty neat.
