### ISSUE TITLE
traverse_in_parallel

### ISSUE THREAD

**Issue by takayama-na** [madmann91/bvh#17]
The below function processes from node of leaf in order.
However, it looks like it is continuing when is_leaf is true.
Is this correct?

bottom_up_algorithm.hpp
void traverse_in_parallel
...
            // Only process leaves
            if (MaintainChildIndices ? children[i] != 0 : bvh.nodes[i].is_leaf)
                continue;
...

**Comment by madmann91** [comment]
I guess you are referring to https://github.com/madmann91/bvh/blob/master/include/bvh/bottom_up_algorithm.hpp#L61.
There is a bug here that somehow was not tested because the template was always instantiated with `MaintainChildIndices` equal to `true`. The intent of this line is to skip indices for which the corresponding node is _internal_ (not a leaf). Hence the condition should really be `MaintainChildIndices ? children[i] != 0 : !bvh.nodes[i].is_leaf`. I'm fixing that and I am working on a test for that.

**Comment by madmann91** [comment]
This should be fixed in commit da63ad7bc72c7ab713e6f3de45b018d3949e4f48. I'm still working on a test for this. Thank you for the bug report!

**Comment by takayama-na** [comment]
I understood.
Thank you for your prompt response!
