### ISSUE TITLE
Question: Which construction method for best single core performance? 

### ISSUE THREAD

**Issue by Jarred-Sumner** [madmann91/bvh#25]
I'm writing a JavaScript BVH library and using your implementation as a reference. Not for ray tracing, but for picking and collisions. The library would be intended to run in a [Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) (a separate long-lived process, much heavier than a thread and only one "CPU" for it)

I'd rather just use WASM and your library directly, but lack of easy shared memory between WASM and JS means copying all the vertex data over from JS to WASM (since the WebGL stuff is in JS) which is tricky because browsers are more memory-constrained than desktop software.

Do you have a suggestion for which construction method to use as a reference? Construction speed is a priority. I'm thinking `bvh::LocallyOrderedClusteringBuilder`, but what do you think?

**Comment by madmann91** [comment]
The linear BVH builder is the fastest, but the resulting BVH quality is really low. Consequently, I concur with your original guess: I recommend implementing PLOC, because it's only a tiny bit slower during construction, but it can produce much better BVHs. The implementation in this library now uses distance matrices to cache the distance between nodes, but if you choose a small enough search radius (approximately below 10), you can just directly compute those without caching, and it will be just as fast and simpler to implement. If that is still not fast enough for you, you can then try to play around with the parameters (search radius, number of morton code bits, ...).

**Comment by madmann91** [comment]
If you only have one core, it might make sense to use/implement a top-down builder like `bvh::BinnedBvhBuilder`, with a small number of bins (8 or less). The quality will be probably equivalent to PLOC (or slightly worse), but it might be a bit easier to implement since you won't need morton codes or radix sort. Of course it's not as easy to parallelize or vectorize, but that should not be a problem for your use case. Alternatively, if you don't use the BVH much, you can also implement/use `bvh::LinearBvhBuilder`, but the quality of the generated BVHs is really low. Here's a small graph of this library with OpenMP disabled (so it's single threaded) and different builders with different parameters (the same path tracer as the one on the front page is used for rendering):
![single_threaded](https://user-images.githubusercontent.com/8089474/103176509-92206400-4872-11eb-8ae2-e006de09b538.png)
Note that the machine used here is different from the one used on the front page, it's a laptop with a 2700U Ryzen CPU.
Using the aforementioned path tracer, here's what the frame times would look like if it was rebuilding the BVH at every frame (keep in mind that 1 sample of the path tracer requires to trace several rays, one for the camera, one for each bounce, and one at each vertex to evaluate the contribution of the light sources):
![single_threaded_full](https://user-images.githubusercontent.com/8089474/103176705-52f31280-4874-11eb-8b3f-f24610c97279.png)
Depending on how many rays you have to trace, the most efficient construction method for that ray budget may be different. However, I still stand by my recommendation to use PLOC, since its performance can be easily improved by parallelization, and the quality of the generated BVH can be further improved by collapsing leaves.

**Comment by Jarred-Sumner** [comment]
Thanks for putting all this work into answering my question, I totally
didn’t expect that.

It won’t be used for ray tracing, so the number of ray intersection tests
will only be about 3 per frame most likely. This is just for picking and
collisions. I want to get the construction time to be < 60ms for a 100k
triangle mesh.

My specific use case is for a smooth (non cube) voxel game, so this BVH
would be constructed after meshing is complete. But it will be an open
source library not tied to my particular use case (and I’ll link to this
repo in the readme)

> if you don't use the BVH much, you can also implement/use
bvh::LinearBvhBuilder, but the quality of the generated BVHs is really low

For BVHs, does quality mean ray intersection time or misses or both? Will
low quality BVHs take a long time to run and get the right answer, or will
they be slow and get the wrong answer?

**Comment by madmann91** [comment]
All BVH construction methods are correct. That means that they produce a BVH that corresponds to the geometry, and that given a correct traversal algorithm produces the right answer (but writing such an algorithm is non-trivial, see e.g. `bvh::RobustNodeIntersector` and the article by T. Ize on the topic). However, the _shape_ of the BVH determines how fast a traversal algorithm can find the answer to a ray-triangle intersection query. Think of this as the same argument to how fast a binary tree search can be: If the tree is a shaped like a comb (e.g. each internal node has a leaf as a child), then search is going to be `O(n)` instead of `O(log(n))`. The same holds for BVHs: If your BVH is a low-quality one, the traversal times are going to be longer.

Given that your ray budget is extremely low, it might make sense to switch to the linear BVH builder. An alternative to that is to build the BVH once and use refitting once the geometry changes. Refitting is the process of updating the BVH nodes to match changes in the geometry. As a result, the hierarchy may be not as efficient as before, but it will now be correct for the updated geometry.

If you design a game, another common optimization is to separate the static geometry (meshes that stay the same) from the dynamic one. Then, you can build a BVH for the static part of the scene using a high-quality BVH builder (e.g. `bvh::LocallyOrderedClustering` combined with `bvh::ParallelReinsertionOptimizer` and `bvh::LeafCollapser`), and use a fast algorithm for the dynamic part (e.g. `bvh::LinearBvhBuilder`).

**Comment by madmann91** [comment]
I am closing this issue. Feel free to re-open if you feel your question hasn't been answered.

**Comment by Jarred-Sumner** [comment]
You answered it thoroughly. Thank you.
