### ISSUE TITLE
Insert primitives into BVH

### ISSUE THREAD

**Issue by rcallagh** [madmann91/bvh#32]
Hi, I'm wondering if the BVH created using this library can insert primitives after construction, or whether the BVH would need to be reconstructed from scratch if new primitives are added to the scene?

Additionally, I'm curious whether it's possible to query the BVH with an AABB to find which nodes overlap with the AABB (I think this may be in the plans in #30)

**Comment by madmann91** [comment]
You can of course insert primitives after construction, but you need to be careful how to do it if you want to still maintain good performance. Right now, if you have several primitives to add to a BVH, you can just build a small BVH on those primitives (e.g. using `bvh::LinearBvhBuilder`), then allocate a larger BVH to hold the original BVH + the small one (you need essentially N + M + 1 nodes where N is the original number of nodes, M is the number of nodes of the small BVH -- the +1 is because you need to allocate a new root node which encompasses both the root node of the original BVH and the one of the small one). Then you can run `bvh::ParallelReinsertionOptimizer` to optimize that a bit.

In general, adding primitives to a BVH is an expensive operation, so it's better to batch primitives changes, or better yet, have more than one BVH: You can create one BVH for static geometry (which does not change), and one (or several) for dynamic geometry. Then you can build a second-level BVH over using those BVHs as primitives. At every frame, the BVHs from dynamic geometry can be completely recomputed, or simply refitted (using e.g. `bvh::HierarchyRefitter`) if only the vertex positions have changed. The top-level BVH also has to be recomputed, but since it's small, it should be pretty fast to build.

Finally, it's of course entirely possible to intersect a BVH computed by this library with an AABB, or any other primitive type (including another BVH). I just haven't found the time to do that yet (as you noticed from issue #30).
