### ISSUE TITLE
Traversal returns All Hits

### ISSUE THREAD

**Issue by OptimisticMonkey** [madmann91/bvh#33]
How hard would it be to modify the traversal algorithm to include all hits?

**Comment by madmann91** [comment]
Hello, and thank you for your interest. The current API supports this, but you have to supply your own intersector. Something like: 
```cpp
template <typename Bvh, typename Primitive, bool Permuted = false>
struct AllHitsPrimitiveIntersector : public PrimitiveIntersector<Bvh, Primitive, Permuted, false> {
    using Scalar       = typename Primitive::ScalarType;
    using Intersection = typename Primitive::IntersectionType;

    struct Result {
        Scalar distance() const { return std::numeric_limits<Scalar>::max(); }
    };

    std::vector<std::pair<size_t, Intersection>> all_hits;

    AllHitsPrimitiveIntersector(const Bvh& bvh, const Primitive* primitives)
        : PrimitiveIntersector<Bvh, Primitive, Permuted, true>(bvh, primitives)
    {}

    std::optional<Result> intersect(size_t index, const Ray<Scalar>& ray) const {
        auto [p, i] = this->primitive_at(index);
        if (auto hit = p.intersect(ray))
            all_hits.emplace_back(i, *hit);
        return std::nullopt;
    }
};
```

**Comment by madmann91** [comment]
Note that the code snippet above is untested. However, it never returns a result on purpose, so that the traversal goes through every primitive that is hit, and does not stop once an intersection is found. After traversing the BVH with this intersector, the member `all_hits` should contain all the primitive hits encountered during traversal.
Also note that this code is significantly slower than the other traversal versions, since it has to store potentially many intersections, and traverse way more nodes of the BVH.

**Comment by OptimisticMonkey** [comment]
Aweseome!  Thank you :-)   Going to try it out

**Comment by madmann91** [comment]
I suppose that it must work, given you have not yet complained about it not working. I will then close the issue. Just re-open if I'm mistaken.
