### ISSUE TITLE
Two questions: MB and primitive splitting

### ISSUE THREAD

**Issue by ib00** [madmann91/bvh#52]
1. Is there a way to deal with motion blur or deforming primitives?

2. For spatial splits builder, what is the general approach to splitting an arbitrary primitive? Just split bbox 
at split point?

**Comment by madmann91** [comment]
Hello,
Here's an answer to your questions:

1. Currently this library does not have a dedicated motion blur builder. This does not mean that you can't do motion blur, however. You can for instance build a BVH with references as primitives: Instead of using the original geometry, you can give the BVH builder a tuple `(index, t0, t1)` which corresponds to the primitive at index `index` between time points `t0` and `t1`. All you have to do is have a way to compute the bounding box and center of that primitive. Of course, this means that you have to choose where to split the motion of your objects (choose how many tuples you create for each primitive, and where to place `t0` and `t1`), which is a bit annoying, but should be doable based on the complexity/length of the motion.
2. For the spatial split builder to work, all it needs is to have a `split` function that, given a plane to split the primitive returns two bounding boxes corresponding to each half (on the left of the plane, and on the right of the plane). See [triangle.hpp](https://github.com/madmann91/bvh/blob/master/include/bvh/triangle.hpp#L64).

I am closing this ticket. Please re-open if you don't think this has been completely answered.
