### ISSUE TITLE
Recovering "split axis" from MiniTreeBuilder

### ISSUE THREAD

**Issue by EricAtPlanGrid** [madmann91/bvh#55]
Hello! I was wondering whether it would be possible to either include as part of the data, or to recover based on the tree, which access a node was split on?

**Comment by madmann91** [comment]
If you need that information for traversal, I recommend using a method that intersects the two children and sorts them based on their distance instead. Otherwise, this information can be obtained by either one of two options:

1. Recovering it from the two bounding boxes and choosing the axis which minimizes `min(max1 - min2, max2 - min1)` (the overlap between the two children)
2. Storing it somewhere by packing it in the BVH node during construction. Since this is not used in the current design, and would take up useful bits from the BVH layout, it is not currently done and would require hacking the library a little.

Also, keep in mind that there might not be any split axis for other builders (e.g. ordered clustering), and that reinsertion will interfere with option 2. In general, BVHs need not be split along one axis, they just have to partition the set of objects in _some way_.

I hope this answered your question. If not, please re-open.
