### ISSUE TITLE
Python bindings available?

### ISSUE THREAD

**Issue by drlukeparry** [madmann91/bvh#86]
Dear Arsène, 

I would like to kindly ask if you are aware of any existing Python bindings for your BVH header library?

I didn't want to reinvent the wheel, but wanted to generate BVH for another project using pybind11 library. This appears to be a neat package, as the intel embrue library is very heavy and problematic for use across many 3D Printing / Additive Manufacturing Projects.

Thank you for your kind contribution in advance,
Luke

**Comment by madmann91** [comment]
I have started a branch for C bindings. You can check the progress here: https://github.com/madmann91/bvh/pull/87

**Comment by madmann91** [comment]
A small set of C bindings to the high-level API have now been merged into master. There is also a small example that shows how to use them to render a simple scene. I will close this question, as I don't quite think that this repository would be the right place to add python bindings, but hopefully the presence of C bindings should make it way easier to expose to other languages, including python.

**Comment by dwastberg** [comment]
Hi

Just thought I'd let you know that I've written a small python library for doing ray/mesh intersection testing that is built on this library. I've started looking at exposing the underlying BVH structure more on the python side, but since I don't really have a use for that at the moment, it hasn't been a focus.  Feel free to take a look and see if it solves your problem: https://github.com/dwastberg/pyraymesh
